
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true


org.gradle.java.home=C:/Users/17046/Downloads/kaleidoscope_sculk-1.2/.buildtools/jdk-21.0.2


minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.248
neo_version_range=[21,)
loader_version_range=[4,)


mod_id=kaleidoscope_sculk
mod_name=Kaleidoscope Sculk
mod_license=BSD 3-Clause License
mod_version=1.4.0
mod_group_id=org.kaleidoscope_sculk
mod_authors=
mod_description=
